---
language: elixir
elixir:
  - 1.7.2
otp_release:
  - 21.0
  - 20.3
  - 19.3
env:
  matrix:
    - NO_THIRD_PARTY_INTEGRATION_TEST=true
    - NO_THIRD_PARTY_INTEGRATION_TEST=false

script:
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.7.2" ]; then mix format --check-formatted --dry-run; fi
  - MIX_ENV=test mix compile && mix test
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.7.2" ] && [ "$TRAVIS_OTP_RELEASE" = "21.0" ]; then mix dialyzer; fi

cache:
  directories:
    - .mix
    - _build

notifications:
  email: false
  slack:
    rooms:
      secure: DThLWGAmfB6pfAXBvfzgPSvQx493BY+L+ppEMBLGervQnGx+Oz7CN7NH2pQxdhC8GpKSt2F59aDduZSYPDiyVQIW3QNY8ANEZqSrw1PJy9D7q4eotlT21Z3jgHfxYGPKj1/1oell2l3WFZlvHdp5DqQQTbBcfWT7cnTR0EnVWuq9+Hwuov5ZLKOziQusS8jACwrrp/bELhNlLNNmCoRfhz9KNmQtPfwvAyydnSdtCoJ/0lQQyfhfJR7B+J46HwILOZBu5eZObF91pVYWXFOZmIMBwtap4j06lZJOanuxZtJu6YHtzg6EIuaZFRSdM4e5N9trWFRPjyeHEm2MOfjwHl9KmvcU9m/4yUMkp7HIu7NeK06R3PjTR0B6IvgCNaV9auct8y4i7ucx4ZkCB3adS57Tt6NeqTprvdvoE4YMMD2/gdwUdI62N1LIpe2caRMrk8iWRnWDha6+o9uWtyY9qppovgZFlwHSqfSZOaUi9XSW89vF7c2t94VAFEr3GBJtXzzoa54YNYRYDvJxLkYoV5btS4ycsJyKfVJLpqQMtxDDFGVU8kGEUFaKXu0igNz2vwwPj1pjw5rnR1pfr0a5550Q+ouAhw9WkpKjH1/AsWsnng4NbKLFWi0hPMUP0uh+9qDZViSjLC1+AhvscFzsXXKTGNcgfBZsK+46z73ETCc=
